//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS()
        {
            this.detallefactura = new HashSet<detallefactura>();
        }
    
        public int C_id { get; set; }
        public string idArticulo { get; set; }
        public string descripcion { get; set; }
        public string idRubro { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> impuestosInternos { get; set; }
        public Nullable<bool> exento { get; set; }
        public Nullable<decimal> precio1 { get; set; }
        public Nullable<decimal> precio2 { get; set; }
        public Nullable<decimal> precio3 { get; set; }
        public Nullable<decimal> precio4 { get; set; }
        public Nullable<decimal> precio5 { get; set; }
        public Nullable<decimal> precio6 { get; set; }
        public Nullable<decimal> precio7 { get; set; }
        public Nullable<decimal> precio8 { get; set; }
        public Nullable<decimal> precio9 { get; set; }
        public Nullable<decimal> precio10 { get; set; }
        public string categoria { get; set; }
        public string barcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallefactura> detallefactura { get; set; }
    }
}
