//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartera
    {
        public int id { get; set; }
        public string REGIONAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MES_TRANSACC { get; set; }
        public string TIPMOV { get; set; }
        public string NUMFAC { get; set; }
        public string LINEA { get; set; }
        public Nullable<System.DateTime> FECFAC { get; set; }
        public string NOMCLI { get; set; }
        public string NOMVEN { get; set; }
        public Nullable<decimal> DEBITO { get; set; }
        public Nullable<decimal> CREDITO { get; set; }
        public Nullable<decimal> DEBITO2 { get; set; }
        public Nullable<decimal> CREDITO3 { get; set; }
        public Nullable<decimal> DEBITO4 { get; set; }
        public Nullable<decimal> CREDITO5 { get; set; }
    }
}
