//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteraDis
    {
        public int id { get; set; }
        public string Codcli { get; set; }
        public string nombre_cliente { get; set; }
        public string fe_fac { get; set; }
        public string fe_des { get; set; }
        public string tp_d { get; set; }
        public string line { get; set; }
        public string nro_docm { get; set; }
        public string ti_desp { get; set; }
        public string fe_vecto { get; set; }
        public Nullable<decimal> corriente { get; set; }
        public Nullable<decimal> vcdo1_15 { get; set; }
        public Nullable<decimal> vcdo16_30 { get; set; }
        public Nullable<decimal> vcdo31_60 { get; set; }
        public Nullable<decimal> vcdo61mayor { get; set; }
        public string vendedor { get; set; }
        public string codvendedor { get; set; }
    }
}
