//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequePagos
    {
        public int idcheque { get; set; }
        public int idpago { get; set; }
        public string numerocheque { get; set; }
        public string banco { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string fecha { get; set; }
    
        public virtual Pagos Pagos { get; set; }
    }
}
