//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int C_id { get; set; }
        public string codigo { get; set; }
        public string codigoOpcional { get; set; }
        public string razonSocial { get; set; }
        public string calleNroPisoDpto { get; set; }
        public string localidad { get; set; }
        public string cuit { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> claseDePrecio { get; set; }
        public Nullable<decimal> porcDto { get; set; }
        public string cpteDefault { get; set; }
        public string idVendedor { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    }
}
