//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallefactura
    {
        public int id { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> cajas { get; set; }
        public Nullable<int> unidades { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> ventabruta { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> venta_neta { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
    }
}
