//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idfactura { get; set; }
        public Nullable<System.Guid> idbranch { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numerofactura { get; set; }
        public string formapago { get; set; }
    }
}
