//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_map_profile
    {
        public int Id { get; set; }
        public Nullable<int> Idprofile { get; set; }
        public Nullable<int> idmap { get; set; }
        public string geo_map_usr_tpo_decrip { get; set; }
        public Nullable<System.DateTime> geo_map_create_date { get; set; }
        public string geo_map_usr { get; set; }
        public string geo_profile_map_status { get; set; }
    
        public virtual geo_map geo_map { get; set; }
        public virtual geo_profile geo_profile { get; set; }
    }
}
