//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_manage
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Geo_latitud { get; set; }
        public string Geo_longitud { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public string usr_web { get; set; }
        public string host_web { get; set; }
        public string imei_id { get; set; }
        public string Route { get; set; }
        public Nullable<int> idcat { get; set; }
    }
}
