//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_usr_profile
    {
        public int Id { get; set; }
        public Nullable<int> Idprofile { get; set; }
        public Nullable<int> iduser { get; set; }
        public string geo_usr_profile_decrip { get; set; }
        public Nullable<System.DateTime> geo_map_create_date { get; set; }
        public string geo_map_usr { get; set; }
        public string geo_usr_profile1 { get; set; }
        public string C_status { get; set; }
    
        public virtual geo_profile geo_profile { get; set; }
        public virtual USER_GEO USER_GEO { get; set; }
    }
}
