//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_ubicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_ubicacion()
        {
            this.geo_img_ubicacion = new HashSet<geo_img_ubicacion>();
        }
    
        public int id { get; set; }
        public int id_img { get; set; }
        public int id_sec { get; set; }
        public string geo_ubu_des { get; set; }
        public string create_usr { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual geo_foto geo_foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_img_ubicacion> geo_img_ubicacion { get; set; }
    }
}
