//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_foto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_foto()
        {
            this.geo_des_foto = new HashSet<geo_des_foto>();
            this.geo_ubicacion = new HashSet<geo_ubicacion>();
        }
    
        public int id { get; set; }
        public string id_img_ext { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public int id_geo_cat { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> id_geo_des_foto { get; set; }
    
        public virtual geo_categoria geo_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_des_foto> geo_des_foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_ubicacion> geo_ubicacion { get; set; }
    }
}
