//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_secuencial
    {
        public int id { get; set; }
        public Nullable<int> sec { get; set; }
        public string id_geo_ub { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> id_geo_ubi { get; set; }
        public Nullable<int> number_sec { get; set; }
    }
}
