//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_profile()
        {
            this.geo_map_profile = new HashSet<geo_map_profile>();
            this.geo_usr_profile = new HashSet<geo_usr_profile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> idaccount { get; set; }
        public string geo_profile_name { get; set; }
        public Nullable<System.DateTime> geo_create_date { get; set; }
        public string geo_create_usr { get; set; }
        public string geo_profile_status { get; set; }
        public string geo_permit { get; set; }
    
        public virtual geo_map_account geo_map_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_map_profile> geo_map_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_usr_profile> geo_usr_profile { get; set; }
    }
}
