//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventariodetalles
    {
        public int id { get; set; }
        public Nullable<int> idinventario { get; set; }
        public string codproducto { get; set; }
        public Nullable<int> valor { get; set; }
        public string unidad { get; set; }
    
        public virtual inventario inventario { get; set; }
    }
}
