//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Engine_IndustrialEntities1 : DbContext
    {
        public Engine_IndustrialEntities1()
            : base("name=Engine_IndustrialEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULOS> ARTICULOS { get; set; }
        public virtual DbSet<Cartera> Cartera { get; set; }
        public virtual DbSet<CarteraDis> CarteraDis { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<Cobranza> Cobranza { get; set; }
        public virtual DbSet<depositos> depositos { get; set; }
        public virtual DbSet<detallefactura> detallefactura { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<MES_DIAS> MES_DIAS { get; set; }
        public virtual DbSet<PEDIDOS> PEDIDOS { get; set; }
        public virtual DbSet<Ventas_netas_historia> Ventas_netas_historia { get; set; }
        public virtual DbSet<ChequePagos> ChequePagos { get; set; }
        public virtual DbSet<PagosDetalles> PagosDetalles { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<Presupuesto> Presupuesto { get; set; }
        public virtual DbSet<Ventas_netas> Ventas_netas { get; set; }
        public virtual DbSet<inventariodetalles> inventariodetalles { get; set; }
        public virtual DbSet<pedidosItems> pedidosItems { get; set; }
    }
}
