//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MardisEngine_TestEntities : DbContext
    {
        public MardisEngine_TestEntities()
            : base("name=MardisEngine_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REAL_STATE_2_CORE> REAL_STATE_2_CORE { get; set; }
        public virtual DbSet<REAL_STATE_2_OBSERVACIONES_EXT_IMG_BLB> REAL_STATE_2_OBSERVACIONES_EXT_IMG_BLB { get; set; }
        public virtual DbSet<REAL_STATE_2_OBSERVACIONES_EXT_IMG_BN> REAL_STATE_2_OBSERVACIONES_EXT_IMG_BN { get; set; }
        public virtual DbSet<REAL_STATE_2_OBSERVACIONES_EXT_IMG_REF> REAL_STATE_2_OBSERVACIONES_EXT_IMG_REF { get; set; }
    }
}
