//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDOS()
        {
            this.pedidosItems = new HashSet<pedidosItems>();
        }
    
        public int C_id { get; set; }
        public string codCliente { get; set; }
        public string fecha { get; set; }
        public string idVendedor { get; set; }
        public Nullable<decimal> totalNeto { get; set; }
        public Nullable<decimal> totalFinal { get; set; }
        public Nullable<decimal> transferido { get; set; }
        public Nullable<decimal> gpsX { get; set; }
        public Nullable<decimal> gpsY { get; set; }
        public Nullable<decimal> facturar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidosItems> pedidosItems { get; set; }
    }
}
