//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSERVICES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REAL_STATE_2_CORE
    {
        public string C_URI { get; set; }
        public string C_CREATOR_URI_USER { get; set; }
        public System.DateTime C_CREATION_DATE { get; set; }
        public string C_LAST_UPDATE_URI_USER { get; set; }
        public System.DateTime C_LAST_UPDATE_DATE { get; set; }
        public Nullable<int> C_MODEL_VERSION { get; set; }
        public Nullable<int> C_UI_VERSION { get; set; }
        public Nullable<bool> C_IS_COMPLETE { get; set; }
        public Nullable<System.DateTime> C_SUBMISSION_DATE { get; set; }
        public Nullable<System.DateTime> C_MARKED_AS_COMPLETE_DATE { get; set; }
        public string RUTA_COD { get; set; }
        public string RUTA_EXISTE { get; set; }
        public Nullable<decimal> OBSERVACIONES_COORD_ACC { get; set; }
        public Nullable<decimal> OBSERVACIONES_COORD_LAT { get; set; }
        public Nullable<decimal> OBSERVACIONES_COORD_LNG { get; set; }
        public string RUTA_NUM_RUTA { get; set; }
        public string IMEI_ID { get; set; }
        public Nullable<decimal> OBSERVACIONES_COORD_ALT { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> END { get; set; }
        public string META_INSTANCE_ID { get; set; }
    }
}
